# API Configuration
api:
  server: "10.28.143.3"
  endpoint: "/api/blueprints/494c107b-3620-4be1-9ffc-1ffc8611482b/revisions"
  polling_interval_seconds: 30
  # Authentication will come from environment variables

backup:
  script_path: "aos_backup"
  parameters: []
  
transfer:
  method: "scp"
  host: "10.28.143.4"
  port: 22
  remote_directory: "~/"
